---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bookstore-web
  description: Fake bookstore web frontend used for Backstage tryouts
spec:
  type: website
  lifecycle: production
  owner: bookstore-team
  system: bookstore
  dependsOn:
    - component:bookstore
